/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./Components/**/*.razor",
    "./Components/**/*.razor.cs",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434654",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        "outline": "#737685",
        "outline-variant": "#c3c6d6",
        "surface-tint": "#0c56d0",
        "primary": "#003d9b",
        "on-primary": "#ffffff",
        "primary-container": "#0052cc",
        "on-primary-container": "#c4d2ff",
        "inverse-primary": "#b2c5ff",
        "secondary": "#525f75",
        "on-secondary": "#ffffff",
        "secondary-container": "#d6e3fe",
        "on-secondary-container": "#58657c",
        "tertiary": "#3e444c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#555b64",
        "on-tertiary-container": "#cdd3dd",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "secondary-fixed": "#d6e3fe",
        "secondary-fixed-dim": "#bac7e1",
        "on-secondary-fixed": "#0e1c2f",
        "on-secondary-fixed-variant": "#3a475d",
        "tertiary-fixed": "#dde3ed",
        "tertiary-fixed-dim": "#c1c7d1",
        "on-tertiary-fixed": "#161c24",
        "on-tertiary-fixed-variant": "#414750",
        "background": "#f8f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e1e2e4",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-sm": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "sidebar-width": "260px",
        "sidebar-collapsed": "72px",
        "max-content-width": "1600px",
      },
    },
  },
  plugins: [],
}